---
- name: Ensure Rainloop directory exists
  ansible.builtin.file: 
    path: "{{ rainloop_install_dir }}"
    state: directory
    owner: "{{ rainloop_user }}"
    group: "{{ rainloop_group }}"

- name: Extract Rainloop files
  ansible.builtin.unarchive:
    src: "{{ rainloop_url }}"
    dest: "{{ rainloop_install_dir }}"
    owner: "{{ rainloop_user }}"
    group: "{{ rainloop_group }}"
    remote_src: True
  
- name: Create Rainloop domain configuration
  ansible.builtin.template:
    src: rainloop-config.j2
    dest: "/var/www/rainloop/data/_data_/_default_/domains/{{ rainloop_domain }}.ini"
    owner: www-data
    group: www-data
    mode: '0644'
  notify: restart apache2

# - name: Install apache2
#   tags: [install]
#   ansible.builtin.include_role:
#     name: apache2
#   vars:
#     apache2_vhosts:
#       - name: rainloop
#         aliases:
#           - mail.
#         http: true
#         https: false
#         document_root: "{{ rainloop_install_dir }}"
#         enabled: true

- name: Install apache2
  tags: [install]
  ansible.builtin.include_role:
    name: apache2

- name: Set Apache vhosts fact
  ansible.builtin.set_fact:
    apache2_vhosts:
      - name: rainloop
        aliases:
          - mail.
        http: true
        https: false
        document_root: "{{ rainloop_install_dir }}"
        enabled: true


